session_name: dotfiles
windows:
    - window_name: git centre
      layout: main-horizontal
      panes:
          - shell_command:
            - cmd: lazygit
            focus: yes
          - shell_command:
              - git
            enter: no
    - window_name: working dir
      focus: yes
      panes:
        - shell_command:
            - cmd: neofetch

