live_config_reload = true

[shell]
program = "tmux"

[window]
    startup_mode = "Maximized"
    opacity = 0.8
    blur = true

[selection]
    save_to_clipboard = true
    semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[scrolling]
    history    = 10000
    multiplier = 4

[font]
    size = 14
    
    [font.bold]
        family = "JetBrainsMono Nerd Font"
        style = "Bold"
        
    [font.bold_italic]
        family = "JetBrainsMono Nerd Font"
        style  = "Bold Italic"
        
    [font.italic]
        family = "JetBrainsMono Nerd Font"
        style = "Italic"
    
    [font.normal]
        family = "JetBrainsMono Nerd Font"
        style = "Regular"
        
    [font.glyph_offset]
        x = 0
        y = 0
    
    [font.offset]
        x = 0
        y = 0

[colors]
    draw_bold_text_with_bright_colors = true

    [colors.bright]
        black   = "#625e4c"
        blue    = "#9d65ff"
        cyan    = "#58d1eb"
        green   = "#98e024"
        magenta = "#f4005f"
        red     = "#f4005f"
        white   = "#f6f6ef"
        yellow  = "#e0d561"

    [colors.normal]
        black   = "#1a1a1a"
        blue    = "#9d65ff"
        cyan    = "#58d1eb"
        green   = "#98e024"
        magenta = "#f4005f"
        red     = "#f4005f"
        white   = "#c4c5b5"
        yellow  = "#fa8419"

    [colors.primary]
        background = "0x1a1b26"
        foreground = "0xa9b1d6"

[env]
    TERM = "xterm-256color"
