import = [
	"~/.config/alacritty/themes/themes/tokyo-night.toml"
]

live_config_reload = true

[keyboard]
	bindings = [
	   { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" }
	]
[[hints.enabled]]
	hyperlinks = true
 	post_processing = true
  	persist = false
	mouse = { enabled = true, mods = "Control" }

[window]
    startup_mode = "Maximized"
    opacity = 0.8
    blur = true

[selection]
    save_to_clipboard = true
    semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[scrolling]
    history    = 10000
    multiplier = 4

[font]
    size = 14
    
    [font.bold]
        family = "JetBrainsMono Nerd Font"
        style = "Bold"
        
    [font.bold_italic]
        family = "JetBrainsMono Nerd Font"
        style  = "Bold Italic"
        
    [font.italic]
        family = "JetBrainsMono Nerd Font"
        style = "Italic"
    
    [font.normal]
        family = "JetBrainsMono Nerd Font"
        style = "Regular"
        
    [font.glyph_offset]
        x = 0
        y = 0
    
    [font.offset]
	x = 0
	y = 0

[colors]
    	draw_bold_text_with_bright_colors = true

[env]
    	TERM = "xterm-256color"
