# import = [
# 	"~/.config/alacritty/themes/tokyo-night.toml"
# ] setup this folder
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
opacity = 0.8
blur = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0
