# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Add new line between shell prompts
add_newline = true 

format = '''
$os|$username $directory$package$shell
$character
'''

right_format = """$cmd_duration $c$python${custom.verilog}${custom.cpp}${custom.sysverilog}"""

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"
vicmd_symbol = "[](bold yellow)"

[username]
style_user = 'green italic'
style_root = 'orange italic'
format = '  :[$user]($style)'
show_always = true
disabled = false

# Hide hostname in remote session

# Custom for Verilog symbol in Prompt
[custom.verilog]
detect_extensions = ['v', 'svf', 'vcd']
symbol = " "
style = 'bold red'
format = 'via [$symbol$output]($style)'
command = ""
disabled = false
ignore_timeout = false

[custom.sysverilog]
detect_extensions = ['svh', 'sv', 'vh']
symbol = " "
style = 'bold red'
format = 'via [$symbol xrun 24.03]($style)'
disabled = false
ignore_timeout = false
# command = "echo "xrun 24.03""

[custom.vhdl]
detect_extensions = ['vhdl']
symbol = " "
style = 'bold red'
format = 'via [$symbol($output)]($style)'
command = ""
disabled = false
ignore_timeout = false

[custom.cpp]
detect_extensions = ['cpp', 'hpp']
symbol = " "
style = 'bold red'
format = 'via [$symbol$output]($style)'
command = "g++ --version | awk 'NR==1 {print $3}'"
disabled = false
ignore_timeout = false

[aws]
symbol = " "
style = 'bold red'

[buf]
symbol = " "
style = 'bold red'

[c]
symbol = " "
style = 'red'

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " 󰌾"
read_only_style = 'red'
# truncation_length = 4
# truncation_symbol = '.../'
home_symbol = ' '

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
style = 'bold cyan'
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "
# ssh_only = false
# format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
# disabled = false

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
# symbol = "(must insert symbol here) "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "


[os]
format = "[ ](bold blue)"
style = "bold blue"
disabled = false

[package]
symbol = "󰏗 "
style = 'bold green'

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

# Enable Transient Prompt (cleans up previous lines)
# [transient_prompt]
# disabled = false

[cmd_duration]
# min_time = 2_000
format = "[ $duration](bold green)"


[shell]
disabled = false
zsh_indicator = "zsh 󰰶"
bash_indicator = "bash "
powershell_indicator = "pws 󰨊"
fish_indicator = "fish 󰈺"
style = 'cyan bold'

# Finish git here on PC
# [git_status]

# Made with ♥︎
